<?php
declare(strict_types=1);

use Migrations\BaseSeed;

class BusinessUsersTenantGroupRoleSeed extends BaseSeed
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $tenantsTable = $this->table('business_users_tenants');
        $tenantsTable->insert([
            [
                'id' => 1,
                'name' => 'SkyBridge Airlines',
                'code' => 'skybridge-airlines',
                'status' => 'active',
                'description' => 'Provider tenant. Owns ticket inventory and sells seats to agents.',
                'settings' => json_encode([
                    'tenant_type' => 'provider',
                    'channel' => 'b2b',
                ], JSON_UNESCAPED_SLASHES),
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 2,
                'name' => 'Nusantara Travel',
                'code' => 'nusantara-travel',
                'status' => 'active',
                'description' => 'Agent tenant. Buys ticket inventory from providers and resells to end users.',
                'settings' => json_encode([
                    'tenant_type' => 'agent',
                    'channel' => 'b2b2c',
                ], JSON_UNESCAPED_SLASHES),
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 3,
                'name' => 'Acme Corporate Travel Desk',
                'code' => 'acme-corporate-travel-desk',
                'status' => 'active',
                'description' => 'End user tenant. Represents a company whose employees request travel through an agent workflow.',
                'settings' => json_encode([
                    'tenant_type' => 'end-user',
                    'channel' => 'corporate',
                ], JSON_UNESCAPED_SLASHES),
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
        ])->saveData();

        $groupsTable = $this->table('business_users_groups');
        $groupsTable->insert([
            [
                'id' => 101,
                'business_users_tenant_id' => 1,
                'name' => 'Inventory Control',
                'code' => 'inventory-control',
                'description' => 'Maintains seat allocation, fare buckets, and allotment controls for provider inventory.',
                'is_default' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 102,
                'business_users_tenant_id' => 1,
                'name' => 'Revenue Management',
                'code' => 'revenue-management',
                'description' => 'Approves pricing changes, quotas, and commercial rules on provider inventory.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 20,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 103,
                'business_users_tenant_id' => 1,
                'name' => 'Provider Operations',
                'code' => 'provider-operations',
                'description' => 'Handles ticket operations, schedule changes, and service escalations for the provider.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 30,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 201,
                'business_users_tenant_id' => 2,
                'name' => 'Sales Team',
                'code' => 'sales-team',
                'description' => 'Sells provider inventory to end users and manages daily retail transactions.',
                'is_default' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 202,
                'business_users_tenant_id' => 2,
                'name' => 'Ticketing Desk',
                'code' => 'ticketing-desk',
                'description' => 'Issues tickets, handles reissue or refund requests, and coordinates with providers.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 20,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 203,
                'business_users_tenant_id' => 2,
                'name' => 'Agent Finance',
                'code' => 'agent-finance',
                'description' => 'Monitors credit limits, settlements, and approval flow for high-value bookings.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 30,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 301,
                'business_users_tenant_id' => 3,
                'name' => 'Travel Requesters',
                'code' => 'travel-requesters',
                'description' => 'Employees who request and purchase trips through the appointed agent.',
                'is_default' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 302,
                'business_users_tenant_id' => 3,
                'name' => 'Approvers',
                'code' => 'approvers',
                'description' => 'Approves business trip requests in a tiered approval flow before ticketing.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 20,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 303,
                'business_users_tenant_id' => 3,
                'name' => 'Travel Desk',
                'code' => 'travel-desk',
                'description' => 'Coordinates approved requests with the agent and manages corporate travel policy.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 30,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
        ])->saveData();

        $rolesTable = $this->table('business_users_roles');
        $rolesTable->insert([
            [
                'id' => 1001,
                'business_users_tenant_id' => 1,
                'name' => 'Provider Staff',
                'code' => 'provider-staff',
                'level' => 10,
                'description' => 'Operational provider user who manages routine inventory tasks.',
                'is_default' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 1002,
                'business_users_tenant_id' => 1,
                'name' => 'Provider Supervisor',
                'code' => 'provider-supervisor',
                'level' => 20,
                'description' => 'First approval level for provider-side inventory and operational changes.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 20,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 1003,
                'business_users_tenant_id' => 1,
                'name' => 'Provider Manager',
                'code' => 'provider-manager',
                'level' => 30,
                'description' => 'Second approval level for pricing and inventory policy changes.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 30,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 1004,
                'business_users_tenant_id' => 1,
                'name' => 'Provider Owner',
                'code' => 'provider-owner',
                'level' => 40,
                'description' => 'Top-level provider user with full business control over ticket inventory.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 40,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 2001,
                'business_users_tenant_id' => 2,
                'name' => 'Agent Staff',
                'code' => 'agent-staff',
                'level' => 10,
                'description' => 'Retail agent user who creates bookings and serves end users.',
                'is_default' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 2002,
                'business_users_tenant_id' => 2,
                'name' => 'Agent Supervisor',
                'code' => 'agent-supervisor',
                'level' => 20,
                'description' => 'Approves special fares, changes, and operational exceptions at the agent level.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 20,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 2003,
                'business_users_tenant_id' => 2,
                'name' => 'Agent Manager',
                'code' => 'agent-manager',
                'level' => 30,
                'description' => 'Second approval level for settlements, overrides, and key customer bookings.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 30,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 2004,
                'business_users_tenant_id' => 2,
                'name' => 'Agent Owner',
                'code' => 'agent-owner',
                'level' => 40,
                'description' => 'Top-level user for the agent business entity.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 40,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 3001,
                'business_users_tenant_id' => 3,
                'name' => 'End User',
                'code' => 'end-user',
                'level' => 10,
                'description' => 'Base traveler role for requesting and buying tickets through the agent.',
                'is_default' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 3002,
                'business_users_tenant_id' => 3,
                'name' => 'Travel Coordinator',
                'code' => 'travel-coordinator',
                'level' => 20,
                'description' => 'Coordinates requests and liaises with the agent after initial approval.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 20,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 3003,
                'business_users_tenant_id' => 3,
                'name' => 'Approver Level 1',
                'code' => 'approver-level-1',
                'level' => 30,
                'description' => 'First approval tier for standard travel requests.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 30,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 3004,
                'business_users_tenant_id' => 3,
                'name' => 'Approver Level 2',
                'code' => 'approver-level-2',
                'level' => 40,
                'description' => 'Second approval tier for high-value or policy exception travel requests.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 40,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'id' => 3005,
                'business_users_tenant_id' => 3,
                'name' => 'Corporate Admin',
                'code' => 'corporate-admin',
                'level' => 50,
                'description' => 'Owns travel policy and final authority for the corporate end-user tenant.',
                'is_default' => false,
                'is_active' => true,
                'sort_order' => 50,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
        ])->saveData();

        $groupRolesTable = $this->table('business_users_group_roles');
        $groupRolesTable->insert([
            [
                'business_users_group_id' => 101,
                'business_users_role_id' => 1001,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 102,
                'business_users_role_id' => 1002,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 102,
                'business_users_role_id' => 1003,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 103,
                'business_users_role_id' => 1004,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 201,
                'business_users_role_id' => 2001,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 202,
                'business_users_role_id' => 2002,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 203,
                'business_users_role_id' => 2003,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 203,
                'business_users_role_id' => 2004,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 301,
                'business_users_role_id' => 3001,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 302,
                'business_users_role_id' => 3003,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 302,
                'business_users_role_id' => 3004,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 303,
                'business_users_role_id' => 3002,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
            [
                'business_users_group_id' => 303,
                'business_users_role_id' => 3005,
                'created' => $now,
                'created_by' => null,
                'modified' => $now,
                'modified_by' => null,
            ],
        ])->saveData();
    }
}